### ISSUE TITLE
Clossing ticket wont kick user

### ISSUE THREAD

**Issue by lunaticsm** [Rocky-pup/Erry#1]
After we clossing the ticket, the user who was opened the ticket wont get kicked.

![close ticket](https://user-images.githubusercontent.com/101097846/169330613-eb4228f9-58d0-4ede-99f1-41944d3e7db2.PNG)

And there's no error console log.

**Comment by Rocky-pup** [comment]
mongo is not creating important data for this actions. When ticket is creating mongo needs to create in "setups" this channel id with user and other. It's not creating so you can see <@undefined>, State: undefined. In code all ok, and idk how to fix
